services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: topdrive
    ports:
      - "5432:5432"
    volumes:
      - topdrive_db:/var/lib/postgresql/data
volumes:
  topdrive_db:
